.PHONY: client client-check client-console serve stop creator upload tests lib-test editor editor-stop stop-editor editor-check gate gate-world gate-character gate-hexworld gate-one gate-rep check fast probe-text probe-split probe-p2 probe-p6 probe-b1a probe-auth pages probe-demo plan-check play play-fast browser port-free

# `lib-test` pipes loft's output through grep, and a pipeline's status is the
# LAST command's — so without pipefail the gate would report grep's success and
# scroll straight past a failing package.
SHELL := /bin/bash
.SHELLFLAGS := -o pipefail -c

PORT ?= 8000
PY ?= python3
LOFT ?= loft
# One job per test FILE for `make fast`. 16 is the measured knee on a 24-core box:
# 8 jobs 22.9 s, 16 jobs 16.5 s, 24 jobs 15.9 s over 113 files. Below the knee the
# cores idle; above it the wall is the slowest single file and nothing else moves.
TEST_JOBS ?= 16

# The loft packages under lib/, in dependency order.
#
# ⚠ THIS LIST IS THE TEST TARGET, so a package missing from it is a package whose
# tests never run. `hex_voxel` and `glb_read` sat outside it for months — 66 tests
# that only ever passed because someone ran them by hand. They are lavition
# packages and take no brand prefix (see CLAUDE.md), which is exactly why a
# `moros_*`-shaped list skipped them.
LIB_PACKAGES = moros_map moros_editor moros_render moros_sim lavition_ui \
               hex_voxel hex_editor hex_part hex_proj hex_mesh glb_read

serve:
	$(PY) -m http.server $(PORT) --directory html &
stop:
	killall $(PY)
creator:
	firefox http://localhost:8000/character-creator.html
upload:
	rm data/pages.zip
	cd html ; zip -9 ../data/pages.zip *
# The JavaScript suite (html/logic.js, dm-logic.js, data.js) under mocha, with
# coverage from c8.
#
# ⚠ THE `overrides` BLOCK IN package.json IS LOAD-BEARING — do not drop it to
# "simplify" the manifest. All six audit findings were transitive under mocha, and
# there is no released mocha that fixes them: `latest` IS the installed 11.7.6, and
# `npm audit fix` proposes 11.3.0, a DOWNGRADE below the declared floor. Upstream's
# real fix is mocha 12, still at rc. So the four are pinned by hand:
#     brace-expansion  ^5.0.8   the ONLY patched version — the advisory range is
#                               <=5.0.7, so the whole 2.x line mocha sits on is in it
#     minimatch        ^10.2.2  REQUIRED BY THE ABOVE, not optional: brace-expansion 5
#                               replaced `module.exports = expand` with a named
#                               export, and minimatch 9 calls the old shape
#     serialize-javascript ^7.0.7   mocha's parallel-mode worker serialisation
#     diff             ^8.0.4   mocha's assertion-failure formatter
#
# ⚠ AND `npm audit` REPORTED 0 VULNERABILITIES ON A BROKEN TREE. Overriding
# brace-expansion alone audits clean and passes the whole suite, while any brace in a
# glob throws `brace_expansion_1.default is not a function` — mocha's default spec
# has no braces, so nothing noticed. If you touch these versions, the check is not
# `npm audit` and not the test count; it is the four probes in STATE.md item 17,
# against the un-overridden tree as the control.
#
# ⚠ `sh: 1: nyc: not found` was TWO faults wearing one message, and fixing only the
# obvious one leaves the target broken on a fresh clone. The script still named `nyc`
# after the project moved to `c8` (which is the move `"type": "module"` forces — nyc
# cannot instrument ES modules), AND a clean checkout has no `node_modules` at all, so
# the runner was missing whatever it was called. Hence the prerequisite: the target
# installs what it needs rather than assuming someone did it by hand.
node_modules: package.json
	npm install
	@touch node_modules

tests: node_modules
	npm test

# Every loft package's own test suite.  `loft test` exits 1 on failure
# (verified), so the `||` makes one red package fail the whole target
# instead of scrolling past.
# ⚠ BOTH BACKENDS, because loft's Goal D says per-backend green is not enough:
# the interpreter and `--native` are two implementations of one language, and a
# library that passes on one and not the other is exactly the silent divergence
# that goal exists to catch. Every suite here reported "ran on the interpreter
# only" until this line existed.
# ⚠ THE RAW OUTPUT IS KEPT BEFORE ANYTHING FILTERS IT. A `loft test` run died with
# `SIGSEGV caught` once and the crash reporter's own diagnostic — the last opcode,
# the pc, the function — went out through this pipeline's `grep` with the warnings.
# One line survived, which is not enough to file with (loft#717). A signal
# handler's output is the one thing a build must not drop: every other line can be
# regenerated by running again, and that is exactly what the crashing run will not
# do. So `tee` first, filter second, and say where the whole thing is when it fails.
# ⚠ WHICH WAY THE ARROW POINTS, checked rather than remembered. lavition may not
# depend on Moros, and moving the gestures out of the server found that backwards
# twice in code that had compiled for months — see tools/layering.sh. It runs
# before the suites because it costs milliseconds and a violation makes the rest
# moot.
layering:
	@sh tools/layering.sh

lib-test: layering | .test-logs
	@for p in $(LIB_PACKAGES); do \
		printf '\n=== %s ===\n' "$$p"; \
		( cd lib/$$p && $(LOFT) test 2>&1 \
			| tee $(CURDIR)/.test-logs/$$p-interpret.log | grep -viE '^  Warning' ) \
			|| { echo "FAILED: $$p (interpreter) — raw output in .test-logs/$$p-interpret.log"; exit 1; }; \
		( cd lib/$$p && $(LOFT) test --native 2>&1 \
			| tee $(CURDIR)/.test-logs/$$p-native.log | grep -viE '^  Warning' ) \
			|| { echo "FAILED: $$p (native) — raw output in .test-logs/$$p-native.log"; exit 1; }; \
	done

.test-logs:
	@mkdir -p $@



# ── the editor (W0) — the build service ───────────────────────────────────
# One loft process serves the client page AND the model channel on one port,
# so an ssh tunnel needs exactly one forward:
#     ssh -L $(EDITOR_PORT):localhost:$(EDITOR_PORT) <this box>
# then open http://localhost:$(EDITOR_PORT)/ in your own browser.
#
# `editor` runs in the foreground (Ctrl-C stops it); `editor-bg` + `editor-stop`
# use a PID FILE rather than `killall`, which would take out every python/loft
# on a box that other agents share.
EDITOR_PORT ?= 18090
EDITOR_PID  := .editor.pid
LOFT_TOOLS  ?= ../loft/tools

# ── One command to try the editor: build, run, open a browser ────────────────
#
# `make play`      native build (fast at runtime, SLOW the first time — it compiles
#                  the whole graphics dependency tree; cached afterwards)
# `make play-fast` interpreted — starts in a second, for a quick look
#
# ⚠ THE BROWSER IS NOT OPENED OVER SSH, deliberately. On a headless session
# `xdg-open` either fails or opens a browser on the machine nobody is sitting at.
# The check is "is there a display", not "is this Linux": a local desktop session
# gets a browser, an SSH session gets the tunnel command it actually needs.
BROWSER_URL := http://127.0.0.1:$(EDITOR_PORT)/

# Free the port before starting. `editor-stop` only knows the PID file, so an
# editor started any other way — by hand, by a gate, by a previous run that was
# interrupted — keeps the port and the next start dies with "Address already in
# use". This looks the port up instead.
#
# ⚠ It kills ONLY a process it can identify as this editor, and BOTH forms have to
# be recognised: interpreted runs carry `editor_server.loft` on the command line,
# while a NATIVE run is a compiled binary called `loft_native_bin_<n>` and carries
# no source name at all. The first version matched only the source, so it refused
# to free the port after `make play` — correctly, since an unrecognised process is
# exactly what must not be killed.
#
# A bare `pkill -f editor_server.loft` is the wrong tool: it matches the shell
# running the command too, and has killed this session once already.
#
# ⚠ AND IT WAITS FOR THE PORT, NOT FOR TWO SECONDS. Killing the process is not the
# same as freeing the address: a gate that closes its socket leaves the server side
# in CLOSE-WAIT, and once the server is gone that connection sits in TIME_WAIT with
# `sport = :18090` — so `bind` fails with "Address already in use" and the panic is
# fatal, because the server does not retry. Measured: the suite died on its THIRD
# gate twice running, at a bind, with two gates green before it; a three-restart
# probe around the same gate showed the lingering CLOSE-WAIT on two runs of three.
# That is the "wait for the server, not the clock" rule this repo enforces on every
# gate, turned on the harness that runs them.
port-free:
	@pid=$$(ss -lptn 'sport = :$(EDITOR_PORT)' 2>/dev/null | grep -oP 'pid=\K[0-9]+' | head -1); \
	if [ -n "$$pid" ]; then \
	  cmd=$$(tr '\0' ' ' < /proc/$$pid/cmdline 2>/dev/null); \
	  if echo "$$cmd" | grep -qE 'editor_server\.loft|loft_native_bin_'; then \
	    kill $$pid 2>/dev/null; \
	  else \
	    echo "port $(EDITOR_PORT) held by pid $$pid, which is NOT the editor — leaving it alone"; \
	    exit 1; \
	  fi; \
	fi; \
	for i in $$(seq 1 90); do \
	  ss -tan "sport = :$(EDITOR_PORT)" 2>/dev/null | grep -q ":$(EDITOR_PORT)" || exit 0; \
	  sleep 1; \
	done; \
	echo "port $(EDITOR_PORT) still held after 90s:"; ss -tan "sport = :$(EDITOR_PORT)"; exit 1

browser:
	@if [ -z "$$DISPLAY" ] && [ -z "$$WAYLAND_DISPLAY" ] && [ "$$(uname -s)" = "Linux" ]; then 	  echo ""; 	  echo "  no display here — this looks like an ssh session, so run on YOUR machine:"; 	  echo "      ssh -L $(EDITOR_PORT):localhost:$(EDITOR_PORT) $$(whoami)@$$(hostname)"; 	  echo "  then open  $(BROWSER_URL)"; 	  echo ""; 	else 	  case "$$(uname -s)" in 	    Darwin)            open "$(BROWSER_URL)" ;; 	    Linux)             xdg-open "$(BROWSER_URL)" >/dev/null 2>&1 ;; 	    MINGW*|MSYS*|CYGWIN*) cmd.exe /c start "" "$(BROWSER_URL)" ;; 	    *)                 echo "  open $(BROWSER_URL) in a browser" ;; 	  esac; 	  echo "  opened $(BROWSER_URL)"; 	fi

# ⚠ `client` FIRST, OR THE BROWSER GETS THE LAST BUILD SOMEBODY REMEMBERED TO MAKE.
# The server is compiled from source every run; the client is a FILE it serves, so an
# edit to `editor_client.loft` is invisible here until `make client` runs. It cost a
# full diagnosis in the gates — a change read as "never runs" through three
# instrumented runs while the code was simply not in the page — and the same trap sat
# in every human-facing target: `play`, `play-fast`, `editor`, `editor-bg`.
play: port-free client
	@echo "building natively (first run compiles the graphics tree — minutes)…"
	@nohup $(LOFT) --native --lib lib/ src/editor_server.loft > .editor.log 2>&1 & echo $$! > $(EDITOR_PID)
	@until grep -q 'drag or A/D' .editor.log 2>/dev/null; do 	  if ! kill -0 $$(cat $(EDITOR_PID)) 2>/dev/null; then 	    echo "editor exited — last lines:"; grep -vE '^warning|^ *\||^ *-->' .editor.log | tail -5; exit 1; fi; 	  sleep 2; done
	@echo "editor up (native) on port $(EDITOR_PORT)"
	@$(MAKE) -s browser

play-fast: port-free client
	@nohup $(LOFT) --interpret --lib lib/ src/editor_server.loft > .editor.log 2>&1 & echo $$! > $(EDITOR_PID)
	@until grep -q 'drag or A/D' .editor.log 2>/dev/null; do 	  if ! kill -0 $$(cat $(EDITOR_PID)) 2>/dev/null; then 	    echo "editor exited — last lines:"; grep -vE '^warning|^ *\||^ *-->' .editor.log | tail -5; exit 1; fi; 	  sleep 1; done
	@echo "editor up (interpreted) on port $(EDITOR_PORT)"
	@$(MAKE) -s browser

# ── the client (plan #16, S1) ─────────────────────────────────────────────
# No `--lib` flag: `web` resolves from the registry (0.3.3), whose tarball carries
# the `wasm/` bridge `--html` needs.
#
# ⚠ If this ever fails again with `web_wasm` unresolved, the cause is a stale
# ~/.loft/lib/web SHADOWING the registry copy — `loft install <dir>` copies only
# loft.toml, src/*.loft, tests/ and native/, so a locally installed library loses
# its wasm bridge (loft-lang/loft#667). `rm -rf ~/.loft/lib/web` is the fix; the
# published package was never at fault.
client:
	$(LOFT) --html --lib lib/ src/editor_client.loft
	@echo "wrote src/.loft/editor_client.html"

editor: client
	$(LOFT) --interpret --lib lib/ src/editor_server.loft

editor-bg: client
	@nohup $(LOFT) --interpret --lib lib/ src/editor_server.loft > .editor.log 2>&1 & echo $$! > $(EDITOR_PID)
	@until grep -q 'listening on port' .editor.log 2>/dev/null; do sleep 1; done
	@echo "editor on http://localhost:$(EDITOR_PORT)/  (pid $$(cat $(EDITOR_PID)))"

# ONE STOP, THREE PLATFORMS, TWO WAYS IN — see tools/editor-stop.sh for why each
# step is spelled differently on each, and why it kills only what it can identify.
# `editor-stop` is kept as an alias because muscle memory and older docs use it.
stop-editor editor-stop:
	@EDITOR_PORT=$(EDITOR_PORT) EDITOR_PID=$(EDITOR_PID) sh tools/editor-stop.sh

# THE GATE — loft's own headless check. Layer 1 fails on any console error;
# Layer 2 screenshots the canvas and counts distinct colours, which is what
# catches "compiles clean, blank canvas".  Control: break the draw and watch
# distinctColors collapse to 1.
# ⚠ IT WATCHED `#gl`, WHICH IS THE DELETED PAGE'S CANVAS. `html/editor.html` named its
# canvas `#gl`; loft's `--html` shell names its own `#c`, and `/` now serves the wasm
# client — so this check was looking for an element that no longer exists on any route.
# The two-renderers pair it belonged to is gone with it: `/` and `/client` are the same
# page. Kept as a route check — that `/` serves the client at all — because that is the
# one thing `client-check` does not cover.
editor-check:
	node $(LOFT_TOOLS)/html_render_check.mjs http://127.0.0.1:$(EDITOR_PORT)/ \
	  --wait-ms 20000 --canvas '#c' --canvas-min-colors 12 --screenshot /tmp/w0.png

# The SAME check against the wasm client (plan #16, S1) — same server, same wire,
# same claim: it drew a world and not a flat sky. The canvas is `#c` because that is
# what loft's `--html` shell names its own, and the wait is longer because the page
# boots a 670 KB wasm before it dials.
#
# ⚠ THIS WAS S1'S DONE-WHEN, and the pair it belonged to no longer exists: with
# `html/editor.html` deleted, `/` and `/client` serve the SAME page. The two checks now
# measure one renderer over two routes, which is worth keeping — a route that stops
# serving the client is a real failure — but it is no longer a comparison, and reading
# it as one would be reading agreement between a thing and itself.
client-check:
	node $(LOFT_TOOLS)/html_render_check.mjs http://127.0.0.1:$(EDITOR_PORT)/client \
	  --wait-ms 20000 --canvas '#c' --canvas-min-colors 12 --screenshot /tmp/w0-client.png

# What the wasm client SAID, when it drew nothing and the check cannot say why.
client-console:
	node tools/page_console.mjs http://127.0.0.1:$(EDITOR_PORT)/client --wait-ms 15000

# ── looking at the world without being at the keyboard ────────────────────
# A PICTURE OF WHAT THE HUMAN IS LOOKING AT. This attaches a headless client and
# screenshots its canvas, so a description of an artefact can be checked instead
# of imagined.
#
# ⚠ It is PASSIVE — it sends no key and no `7:` placement, so the SHARED character
# does not move and a person already driving this server is undisturbed. That is
# the whole reason it is separate from the gates, which all drive.
#
#   make shot                            the wasm client, to shot.png
#   make shot PAGE=/ CANVAS='#gl'        the JavaScript one, for comparison
SHOT   ?= shot.png
PAGE   ?= /client
CANVAS ?= \#c
shot:
	@node $(LOFT_TOOLS)/html_render_check.mjs http://127.0.0.1:$(EDITOR_PORT)$(PAGE) \
	  --wait-ms 20000 --canvas '$(CANVAS)' --canvas-min-colors 2 --screenshot $(SHOT)
	@echo "wrote $(SHOT)"

# IS THE GROUND WATERTIGHT, AND IS IT SMOOTH? Two different questions that look
# identical on screen — a crack shows background through a gap, a facet is a real
# fold in the surface — and they have completely different fixes. Reads the drawn
# triangles off the wire; also passive.
seam:
	@node tools/seam.mjs $(EDITOR_PORT)

# THE SAME QUESTION, ASKED WHILE THE WORLD IS MOVING. The settled world is the one
# state in which a rebuild-order crack cannot appear, so `seam` alone will always
# call a transient artefact clean. Run this, then raise a hill while it watches.
WATCH ?= 20
seam-watch:
	@node tools/seam.mjs $(EDITOR_PORT) --watch $(WATCH)

# ── the editor's gates, split by what they are allowed to break ───────────
# world/     — drive the character by PLACING it; measure terrain, streaming,
#              levelling. Must not depend on locomotion.
# character/ — drive it by WALKING; measure the character itself. Expected to
#              churn as locomotion grows a step limit, a fall, collision.
# Each probe gets a FRESH SERVER: state persists (position, yaw, peaks, the
# level flag), so back-to-back runs are not independent.
# ⚠ TWO failures live here, both found by a suite that hung for forty minutes.
#
# 1. It called `editor-stop`, which knows only the PID FILE — so it was a no-op
#    against an editor started any other way (`play-fast`, a previous gate loop,
#    by hand). That editor kept the port, the gate's own server died on bind, and
#    the loop below waited for a readiness line that was never coming.
# 2. The readiness loop had NO failure path. A server that failed to start looked
#    exactly like a server still starting, forever. Silence is not success: the
#    wait must end in a ready line OR a named failure, never in neither.
#
# 3. It waited for the BANNER, which the editor prints BEFORE it binds. A server
#    that then died on "address already in use" had already written the line the
#    wait was watching for — so the wait went green, the gate connected to the
#    PREVIOUS server, and every gate after the first talked to a stale world. The
#    readiness signal has to be the thing that is only true once the socket is
#    actually listening.
#
# So: free the port by PORT (`port-free` identifies the process as this editor),
# wait for the LISTENING line rather than the banner, and bound the wait — 60s,
# then print the log and fail the gate run.
GATE_RESTART = $(MAKE) -s port-free >/dev/null 2>&1; sleep 1; \
  : > .editor.log; \
  nohup $(LOFT) --interpret --lib lib/ src/editor_server.loft > .editor.log 2>&1 & \
  for i in $$(seq 1 60); do \
    grep -q 'listening on port' .editor.log 2>/dev/null && break; \
    grep -qi 'cannot bind port' .editor.log 2>/dev/null && break; \
    sleep 1; \
  done; \
  if ! grep -q 'listening on port' .editor.log 2>/dev/null; then \
    echo "GATE HARNESS: the editor never listened — last 20 lines:"; \
    grep -vE '^warning|^ *\||^ *-->|^ *=' .editor.log | tail -20; exit 1; \
  fi

# hex_voxel's exact-size proofs run as a PROGRAM, not under `loft test`: several
# save-and-measure tests in one test file hang the harness (see
# lib/hex_voxel/probe/sparsity.loft). Same assertions, same exactness, a runner
# that works.
gate-hexworld:
	@printf '%-34s ' "hex_voxel/probe/sparsity"; \
	  $(LOFT) --lib lib/ lib/hex_voxel/probe/sparsity.loft | tail -1
	@printf '%-34s ' "hex_voxel/probe/edgehold"; \
	  $(LOFT) --lib lib/ lib/hex_voxel/probe/edgehold.loft | tail -1
	@printf '%-34s ' "moros_map/probe/slopeline"; \
	  $(LOFT) --lib lib/ lib/moros_map/probe/slopeline.loft | tail -1

# ⚠ ONE SERVER PER GATE, ALL AT ONCE — see tools/run-gates.sh for the why. The
# serial version took 40+ MINUTES for 28 gates that need 87 seconds between them,
# and it held port 18090 throughout so nobody could touch the editor meanwhile.
# `GATE_JOBS` is how many at a time; each gets its own port from `GATE_PORT_BASE`.
GATE_JOBS ?= 10

gate-world:
	@GATE_JOBS=$(GATE_JOBS) sh tools/run-gates.sh tools/gates/world/*.mjs

gate-character:
	@GATE_JOBS=$(GATE_JOBS) sh tools/run-gates.sh tools/gates/character/*.mjs

# ── ⚠ THE FAST PATH — USE THIS WHILE ITERATING, NOT `make gate` ──────────────
#
# `make gate` is 44 gates and takes 10–20 minutes. It is the thing you run BEFORE
# YOU COMMIT, once. It is not an iteration tool, and using it as one is how a
# session spends an hour proving something a one-minute run already showed.
#
#   make gate-one G="cache"              one gate, ~1 min
#   make gate-one G="walk hipskin"       several, by bare name, either directory
#   make gate-rep G="cache" N=5          the SAME gate five times — the flake hunt
#   make check P=hex_part                layering + one package, interpreter only
#   make check P=hex_part G="part_bind"  …and the gates that cover it
#
# ⚠ `gate-rep` IS THE INSTRUMENT FOR A FLAKE, and it exists because the obvious
# alternative is wrong: a flake in ONE gate is not evidence you gather by running
# the other 43 again. Five runs of one gate is five minutes; five full suites is
# an hour and a half, and says no more about that gate.
gate-one:
	@test -n "$(G)" || { echo 'usage: make gate-one G="cache walk"'; exit 2; }
	@GATE_JOBS=$(GATE_JOBS) sh tools/run-gates.sh \
	  $(foreach g,$(G),$(wildcard tools/gates/*/$(g).mjs))
	@$(MAKE) -s stop-editor >/dev/null

gate-rep:
	@test -n "$(G)" || { echo 'usage: make gate-rep G="cache" N=5'; exit 2; }
	@n=$${N:-5}; i=1; bad=0; \
	  while [ $$i -le $$n ]; do \
	    printf 'run %s/%s ' "$$i" "$$n"; \
	    if GATE_JOBS=$(GATE_JOBS) sh tools/run-gates.sh \
	         $(foreach g,$(G),$(wildcard tools/gates/*/$(g).mjs)); \
	      then echo 'ok'; else echo 'FAILED'; bad=$$((bad+1)); fi; \
	    i=$$((i+1)); \
	  done; \
	  $(MAKE) -s stop-editor >/dev/null; \
	  echo "gate-rep: $$bad of $$n failed"; \
	  [ $$bad -eq 0 ]

# ── ⚠ THE HOT PATH — run this after every step; it starts NO servers ─────────
#
# `make fast` is layering plus every package's tests, one job per test FILE, on the
# interpreter. 113 files, and measured on this box: **16.5 s** at 16 jobs against
# ~140 s for the same tests serially, because the files are independent — `loft test`
# over `hex_part` and the sum of its sixteen files run one at a time agree at 35-39 s,
# so the parallelism costs nothing to buy.
#
# ⚠ NO GATES, DELIBERATELY, AND THAT IS THE POINT OF THE SPLIT. Every gate starts a
# server, waits for a port and drives a world; 44 of them are minutes. A check you run
# after each step must not do that, and a check that takes minutes is one you stop
# running. The gates are `make gate` and they belong to CI and to the moment before a
# commit — not to the loop.
#
# ⚠ AND NOT `--native`, ALSO DELIBERATELY. `make lib-test` is what runs both backends
# and it stays the pre-commit proof: the two are two implementations of one language,
# and loft#760 took `hex_voxel` from 114 green to 96 failed while `--native` passed all
# 114 on the same source. This is the fast loop, not the proof.
#
#   make fast                     the whole tree
#   make fast P=hex_part          one package (or several, quoted)
#   TEST_JOBS=8 make fast         fewer jobs, for a loaded box
#   TEST_VERBOSE=1 make fast      per-file seconds
fast:
	@sh tools/layering.sh
	@TEST_JOBS=$(TEST_JOBS) sh tools/run-tests.sh $(P)

check:
	@sh tools/layering.sh
	@test -n "$(P)" || { echo 'usage: make check P=hex_part [G="part_bind"]'; exit 2; }
	@printf '=== %s ===\n' "$(P)"
	@cd lib/$(P) && $(LOFT) test 2>&1 | grep -viE '^  (Warning|Advice)'
	@if [ -n "$(G)" ]; then $(MAKE) -s gate-one G="$(G)"; fi

# ⚠ THE SUITE STOPS WHAT IT STARTED. Each gate gets a fresh server and the last one
# used to be left running — for days, at 76% of a core once a client had connected
# and left. A suite that leaves a process behind on a shared box is not finished.
# ⚠ ONE POOL, NOT TWO BATCHES. Split into world-then-character, the suite pays the
# slowest gate of each half in series; as one pool it pays the slowest gate once.
# Measured: 2m33 split, 1m30 pooled, for the same 28 gates and the same verdicts.
# ⚠ S7'S CLAIM, CHECKED: the same script builds the same scene with and without a
# server. `editor_run` drives `hex_editor`'s gestures directly and the socket path
# drives them through the editor, so the two agree only if the gestures really are
# the one implementation — which is the whole reason they moved out of the message
# loop. It compares the ACK, because that is the editor's own reckoning of what it
# built, and a divergence in cells, edges or ridge names which one moved.
# ⚠ THE FRAME ITSELF, AS NUMBERS — and it IS in `make gate` now, as
# `tools/gates/world/camera_indoors.mjs`. This target is the same script by hand,
# for when the pictures are what you want rather than the verdict. Every wrong turn
# in the camera work came from reading a picture by eye; this counts the pixels
# instead, classifying by chromaticity so a lit surface and a shadowed one land in
# the same bucket.
#
# Three rows now, and the middle one is the direct test of what was actually broken:
#
#   cam <lo> <hi>       where the EYE is, off the `C:` matrix the renderer used
#   frame <sub> <max>   the subject at least 0.5% of the frame, no surface over 60%
#
# What it read on the way, and every line of it was measured:
#
#   before          outside 1.54%/grass 53%   floor 0.09%/masonry 78%   corner 10.6%/78%
#   camera on wire  outside unchanged         floor 10.6%/masonry 50%   corner 2.7%/61%
#   floor drawn     outside unchanged         floor 10.6%/masonry 71%   corner 2.7%/77%
#   floor separable outside unchanged         floor 10.6%/masonry 47%   corner 2.7%/48%
#
# ⚠ THE THIRD ROW IS THE ONE TO READ. Drawing the missing floor made the gate REDDER,
# because `masonry` was wall AND floor in one bucket — the fix was owed to the
# instrument before the threshold over it could mean anything.
camera-frame:
	@$(MAKE) -s port-free >/dev/null 2>&1; : > .editor.log
	@nohup $(LOFT) --interpret --lib lib/ src/editor_server.loft > .editor.log 2>&1 & \
	 until grep -q 'listening on port' .editor.log; do sleep 0.3; done; \
	 node tools/script.mjs tools/scripts/indoors.keys --shots; rc=$$?; \
	 $(MAKE) -s stop-editor >/dev/null; exit $$rc

# Plan 17 `A2.1` — BUILD THE AUTHORED PARTS FROM THE PROCEDURAL GESTURES.
#
# `src/part_build.loft` runs `stencil_place` once, cuts the result with
# `part_from_region` and writes `data/parts/house/cottage.hxw`. ⚠ It VERIFIES what
# it wrote — reloads the file, compares through `part_diff`, reads `PART` and
# `ANCH` back — and asserts rather than printing, so a broken part stops here
# instead of reaching whatever opens it next.
#
# The output is COMMITTED. A part is content, not a build artifact: #18 `B5` lists
# what is in `data/parts/`, and a catalogue that is empty until somebody runs a
# make target is a catalogue that is empty. ⚠ Committing it is only sane because
# the build is DETERMINISTIC — same bytes, same md5, every run, since `τ` counts
# the gestures rather than the seconds. A file that changed each run would put a
# 64 KB diff in every commit that happened to touch it.
#
# ⚠ STDERR IS FILTERED, NOT DISCARDED. `2>/dev/null` hid the loft advice AND the
# assertion message, so a mutant that broke the part failed the build with nothing
# said — which is a gate you cannot act on. The refusal is printed and only the
# advice is dropped.
# ⚠ AND `src/prop_build.loft` IS THE SECOND HALF, plan 17 `A6.2`: a statue, a
# plinth and the shrine that puts one on the other — §P5's OTHER kind of part, in
# the same library and in the same sockets. It writes a `.glb` as well as three
# `.hxw`, all four committed and all four rebuilt byte-identically, and its gate is
# a `part_expand` rather than a re-read: three files that load are not a statue on
# a plinth. ⚠ `PROP_OUT` redirects it, the way `PART_OUT` redirects the cottage.
parts:
	@$(LOFT) --interpret --lib lib/ src/part_build.loft 2>.parts.err \
	  || { echo "PARTS: the part it built is not the part it wrote"; \
	       grep -A6 '^error:' .parts.err | head -20; \
	       rm -f .parts.err; exit 1; }
	@$(LOFT) --interpret --lib lib/ src/prop_build.loft 2>.parts.err \
	  || { echo "PARTS: the statue is not on the plinth"; \
	       grep -A6 '^error:' .parts.err | head -20; \
	       rm -f .parts.err; exit 1; }
	@rm -f .parts.err

headless-same:
	@SCRIPT=tools/scripts/house.keys WORLD=headless $(LOFT) --lib lib/ src/editor_run.loft 2>/dev/null \
	  | grep -oE 'house placed [0-9]+ cells, [0-9]+ wall edges, ridge at [0-9]+' > .headless.txt || true
	@$(MAKE) -s port-free >/dev/null 2>&1; : > .editor.log
	@nohup $(LOFT) --interpret --lib lib/ src/editor_server.loft > .editor.log 2>&1 & \
	 until grep -q 'listening on port' .editor.log; do sleep 0.3; done; \
	 node tools/script.mjs tools/scripts/house.keys >/dev/null 2>&1; \
	 grep -oE 'house [0-9]+ cells' .editor.log | head -1 > /dev/null; \
	 grep -oE 'house placed [0-9]+ cells, [0-9]+ wall edges, ridge at [0-9]+' .editor.log \
	   | head -1 > .served.txt || true
	@$(MAKE) -s stop-editor >/dev/null
	@if [ ! -s .headless.txt ]; then echo "HEADLESS: the runner placed no house"; exit 1; fi
	@if ! diff -q .headless.txt .served.txt >/dev/null 2>&1; then \
	  echo "HEADLESS: the same script built different scenes"; \
	  echo "  headless: $$(cat .headless.txt)"; \
	  echo "  served:   $$(cat .served.txt)"; exit 1; fi
	@rm -f .headless.txt .served.txt

# SHOW THE GUARDS, AND CHECK THEM. Every S3 probe, each printing its own verdict, and
# the ones that draw a map draw it here — the guard's decisions as a picture rather than
# a count. `probe/s3/README.md` says why that distinction earned its own target.
guards:
	@sh probe/s3/run.sh

# B1.1 (plan 18) — does the text bridge reach the canvas, on BOTH targets?
# ⚠ Spawns headless Chrome and an xvfb display; both are cleaned up by the script.
probe-text:
	@sh probe/b1/run.sh

# THE PRE-FLIGHT FOR STARTING A PLAN — are its steps small AND validated?
#   make plan-check P=22-pages-client
# ⚠ DELIBERATELY NOT IN `make fast`. It is run at ONE moment — when a plan stops
# being a design and starts being work. A design may be rough until then, and a
# gate that demanded cut steps of every idea is one people route around.
plan-check:
	@sh tools/plans.sh $(P)

# P2 (plan 22) — can OUR javascript talk to loft inside a `--html` page?
# The interim storage bridge (`W5`) rests entirely on this. Spawns headless Chrome
# and cleans it up; reads the verdict out of the PAGE's own `<pre>`, not out of a
# value this side computed.
probe-p2:
	@sh probe/p2/run.sh

# P6 (plan 22) — DOES A `--html` PAGE HAVE A FILESYSTEM, AND DOES A WORLD SAVED IN
# IT SURVIVE A RELOAD? The design measured `--html` binding 0 of 20 `fs_*` names and
# wrote `W5`, an interim shim, on that premise. loft#851 landed; this is what says
# so about the INSTALLED toolchain rather than about a changelog, and it retires
# `W5`. Drives the page twice over http AND from `file://`, with the interpreter as
# the oracle. `P6_SABOTAGE=persist` is the control.
probe-p6:
	@sh probe/p6/run.sh

# B1a (plan 22) — DOES THE CLIENT SEND WHAT IT ALWAYS SENT, now that its keys name
# VERBS instead of wire messages? ⚠ NOTHING ELSE CHECKS THIS: `make gate` drives the
# server through script.mjs and `make client-check` counts colours in a picture, so
# neither presses a key in the client at all. The instrument is two things, because
# each is blind on its own — the server's println stream cannot tell a fence from a
# wall, and the saved world cannot tell one opening profile from another.
# `B1A_BASELINE=1` rewrites the committed baseline; `B1A_SOURCE=<file>` builds a
# different client, which is how the sabotages run.
probe-b1a:
	@sh probe/b1a/run.sh

# B2 (plan 22) — ASSEMBLE `_site/`, THE QUICK-START DEMO. It is a COPY of the client
# engine build and asserts it arrived verbatim: the design's rule is that the demo and
# the page the server serves are one artifact, because two would have to be kept in
# step. Refuses an engine older than its own sources rather than shipping last week's
# editor behind a build step.
pages:
	@node tools/build-pages.mjs

# B2/B3 (plan 22) — DOES THE DEMO OPEN FROM A DISK? `_site/index.html` over `file://`
# with no listener at either end: it boots, decides it is on its own, draws its own
# world and a key WRITES into it. ⚠ The first check here that needs no port at all.
# `DEMO_SABOTAGE=emptypage` is `B3`'s own warning made runnable (a page with the right
# elements and no editor); `DEMO_SABOTAGE=deadkey` presses a key with no verb, so a
# check that credits the passage of time with a gesture stays green.
probe-demo: pages
	@sh probe/b2/run.sh

# B1b.1a (plan 22) — DOES THE PANEL SAY WHICH AUTHORITY IT HAS? The status line was
# a literal reading `connected`, set at panel construction before any socket existed,
# and it went on saying so with the server down. Two runs over the SAME page bytes:
# one against the real server, which sees the panel MOVE when the socket opens, and
# one against a static server with no `/ws`, which sees a client that never claims a
# connection it does not have. ⚠ Neither run can make the other's claim.
# `AUTH_SABOTAGE=literal|nodirty|assume` runs the three controls.
probe-auth:
	@sh probe/b1b/auth.sh

# L6.3 (plan 19) — HOW MUCH OF THE SPLIT IS LEFT, as a compile rather than an opinion.
# Stages a lavition-only `lib/` and `--check`s all five programs against it. Answers
# in ~30 s, which is why it is a target of its own and not part of `make fast`:
# `tools/layering.sh` carries the same claim as a cheap import ratchet on every run,
# and this is the decisive backstop that proves the ratchet matches what compiles.
probe-split:
	@sh probe/l6/run.sh

# K1 (plan 22) — DOES A SCRIPT SAYING `verb` BUILD WHAT THE SAME SCRIPT SAYING `key`
# BUILT? Both readers, compared exactly, plus the control that says why the obvious
# instrument (diff the world) is blind to the one mistake a conversion makes.
# `K1_WIRE=0` skips the server half and needs no port.
probe-verbs:
	@sh probe/k1/run.sh

# K2 (plan 22) — DOES A CONVERTED SCRIPT BUILD WHAT IT BUILT BEFORE? The eight
# scripts that press an opening key have NO gate between them, so this is their only
# check: each one beside its pre-conversion baseline, through a server, compared on
# the sentences, the saved world AND the kinds — because the first two are blind to
# a niche's depth. `sh probe/k2/run.sh niche` runs one.
probe-convert:
	@sh probe/k2/run.sh

gate:
	@GATE_JOBS=$(GATE_JOBS) sh tools/run-gates.sh \
	  tools/gates/world/*.mjs tools/gates/character/*.mjs
	@$(MAKE) -s stop-editor >/dev/null
