// ⚠ CHECKED AND LEFT WHOLE — every claim is about a chain of things outside the store.
// A gesture edits, a save writes a file under a name that did not exist, the server's
// sweep notices it, the catalogue is re-sent unasked, the new row sorts first so every
// other row moved, and it arrives OFFERED rather than greyed. That is the editor,
// the filesystem and the wire in one line, and no part of it is arithmetic over a world.
//
// The part FORMAT it writes is `hex_part`'s and is tested there.
// A PART THAT DID NOT EXIST BEFORE — AUTHORED, LISTED, AND PLACED IN ONE SESSION.
//
// Plan 17 `A7.3e`, and it is the acceptance test for the whole plan: *a house
// authored end-to-end without touching loft*. Everything before it proved a half —
// `A7.3a` that a part can be opened, `A7.3c` that it saves back, `A7.1` that the
// catalogue can grow — and none of them joined the two ends, which is where the
// defects were.
//
//   A7.3e-i     a save under a name that did not exist puts the part on disk and
//               the LIBRARY follows: `N:` names it, and every `W:` row is
//               re-addressed because a row index is positional
//   A7.3e-ii    ⚠ the new part is a DIFFERENT part: what was authored in part
//               mode is in the cells `14:<roof>,<new>` stamps, and the part it
//               came from still does not have it
//   A7.3e-iii   ⚠ it carries its OWN name. A save-as used to keep the ancestor's
//               `PART.name`, so `house/cottage` saved as `house/annexe` announced
//               itself as *'cottage'* at every placement and two rows of the
//               catalogue claimed one name — §C2 says a name is unique per kind
//   A7.3e-iv    ⚠ A NEW FAMILY IS A THING AN AUTHOR MAKES, and this is the one
//               that was losing work. `8:newfam/thing` reported *"saved — 1
//               chunks, 2 sections"*, renamed the subject line and re-anchored the
//               edit clock over a file that was never created: `file()` on a path
//               whose directory is missing hands back a usable handle and every
//               write goes to stderr. `hex_world` answers `WS_IO` now and the
//               editor makes the directory
//   A7.3e-v     ⚠ and a name the CATALOGUE could never show is refused before the
//               bytes go anywhere. `8:a/b/c` landed on disk and `part_list` walks
//               one level, so the part was in the library and in no catalogue —
//               placeable by nothing, and every count agreeing
//
// ⚠ THE ACCEPTANCE HOUSE IS NOT `house/cottage`. That part is GENERATED by
// `src/part_build.loft` and `make parts` verifies it byte-identically, so a
// cottage authored here would be reverted by the next build and the failure would
// read as flakiness rather than as the collision it is. The cottage is the thing
// opened; what is authored is a new name with no generator.
//
// ⚠ IT WRITES INTO `EDITOR_PARTS`, WHICH IS THE GATE'S OWN COPY of the library —
// `tools/run-gates.sh` hands every gate one. This gate adds parts on purpose, and
// doing that to `data/parts/` would leave a tree two agents share dirty.
import { readdirSync, existsSync } from 'node:fs';
import { connect, send, ask, said, until, quiet, absenceWindow, checker, verdict } from '../lib.mjs';

const ROOT = process.env.EDITOR_PARTS ?? 'data/parts';

const check = checker();

// ⚠ THE AUTHORED PART MUST SORT FIRST, and that is the whole of `A7.1`'s row
// argument reused: a catalogue row index is positional, so an insert at the FRONT
// renames every row after it. A part inserted at the END would pass a server that
// re-addressed only the new row.
//
// ⚠ THIS WAS `house/annexe` AND THE LIBRARY OUTGREW IT. `A5.2` added a `door/`
// family, which sorts before `house/`, so the check went red naming the new
// content — the gate doing exactly its job, and a reminder that this assertion is
// a claim about the WHOLE library rather than about the part it authors. Any name
// chosen here is a hostage to the next family somebody adds; what keeps it honest
// is that the failure is loud and says which part took first place.
const FROM = 'house/cottage';
const NEW  = 'aaa_annexe/wing';
const FAM  = 'annex/lean_to';        // a family directory that does not exist yet


const g = await connect();
g.ws.send('1:');
// ⚠ WAIT FOR THE SERVER, NOT FOR A CLOCK. This was `await wait(2000)` — a guess at
// how long the opening burst takes, so a loaded box made it a guess that was wrong.
// Every gesture below waits for its own acknowledgement; this only has to see the
// server answer at all, and it SAYS SO if it never does.
await until(() => g.says.length >= 1, 'the server never answered 1:');

// ⚠ WAIT FOR THE ANSWER, NOT FOR A CLOCK — `A7.3d`'s finding, and it is the third
// face of the `GATE_JOBS` flake. A gate written with fixed sleeps passes alone and
// fails at four jobs, because four interpreted servers answer slower than the
// sleep: it reports the machine rather than the claim. Polling is also faster when
// the box is idle.
// One implementation of *wait for the answer* now — `lib.mjs`'s `send`.
const stepFor = (msg, prefix, maxMs = 12000) => send(g, msg, [prefix], maxMs);
const askOne = (msg, prefix) => ask(g, msg, prefix);

// Wait for the library sweep to notice, rather than sleeping through it: the
// server checks once a second and says so when the set moved.
async function libraryFollows(maxMs = 12000) {
  const before = g.cats.length;
  for (let waited = 0; waited < maxMs; waited += 100) {
    if (g.cats.length > before) { await absenceWindow(400, 'no event marks this — see the check below'); return true; }   // let the W: land
    await absenceWindow(100, 'no event marks this — see the check below');
  }
  return false;
}

const partsOf = (n) => (n ?? 'N:').slice(2).split(';').filter(Boolean)
    .map((r) => r.split('|')).filter((f) => f[0] === 'part');
const onDisk = () => {
  const out = [];
  for (const e of readdirSync(ROOT, { withFileTypes: true })) {
    if (e.isDirectory()) {
      for (const f of readdirSync(`${ROOT}/${e.name}`)) {
        if (f.endsWith('.hxw')) out.push(`${e.name}/${f.slice(0, -4)}`);
      }
    } else if (e.name.endsWith('.hxw')) out.push(e.name.slice(0, -4));
  }
  return out.sort();
};

// ⚠ THE FIXTURE, ASSERTED. Everything below compares against the library as it
// was; if `house/cottage` stopped being there, or `house/annexe` already existed,
// every check would be measuring something else.
check(existsSync(`${ROOT}/${FROM}.hxw`), `the part to author from is there (${FROM})`);
check(!existsSync(`${ROOT}/${NEW}.hxw`), `and the new one is not, yet (${NEW})`);
const listed0 = partsOf(g.cats[0]).map((f) => f[1]);
check(listed0.length > 0 && !listed0.includes(NEW),
      `the catalogue arrived without it (${listed0.join(',')})`);

// ── author it ───────────────────────────────────────────────────────────────
let lines = await stepFor(`44:${FROM}`, `part '${FROM}'`);
check(said(lines, `part '${FROM}'`).includes('opened'), 'the part opens');

// ⚠ AN EDGE, BECAUSE THE READ-BACK HAS TO BE AIMED — `A7.3c`'s finding. `5:`
// raises AHEAD of the walker, so `26:0,0` under their feet answers the same before
// and after; `24:` writes an edge of the cell the walker is standing IN, which
// `16:` reads back at exactly that cell.
const authoredBefore = await askOne('16:0,0', 'walls ');
await stepFor('24:0,wall', 'edge ');
const authored = await askOne('16:0,0', 'walls ');
// The instrument, checked against something it should find: with no edit, *the
// authored thing arrived* below compares nothing.
check(authored !== authoredBefore,
      `the gesture changes the part (${authoredBefore} → ${authored})`);

const camsBefore = g.cams.length;
const saved = await askOne(`8:${NEW}`, 'part ');
check(saved.includes('saved'), `it saves under a name that did not exist: ${JSON.stringify(saved)}`);
check(existsSync(`${ROOT}/${NEW}.hxw`), `and the file is on disk (${NEW}.hxw)`);

// ── A7.3e-i — the library follows, while the editor is still running ────────
check(await libraryFollows(), 'the catalogue is re-sent without being asked');
const after = partsOf(g.cats[g.cats.length - 1]).map((f) => f[1]);
check(after.includes(NEW), `and it names the new part (${after.join(',')})`);
check(after.length === listed0.length + 1,
      `the list grew by exactly one (${listed0.length} → ${after.length})`);
check(after[0] === NEW, `and it sorts FIRST, so every other row moved (${after[0]})`);
// ⚠ EVERY ROW'S PICTURE CAME AGAIN. A `W:` leads each part's thumbnail set and
// addresses a ROW; re-sending only the new one leaves every later picture aimed at
// its neighbour — all drawn, all but one wrong, every count agreeing.
const freshRows = new Set(g.cams.slice(camsBefore).map((s) => s.slice(2).split(';')[0]));
check(freshRows.size === after.length,
      `every row's thumbnail was re-addressed (${freshRows.size} of ${after.length})`);
// The availability column, because a part nobody can select is not in the library
// in any sense that matters.
const avail = partsOf(g.cats[g.cats.length - 1]).find((f) => f[1] === NEW);
check(avail !== undefined && avail[2] === '1',
      `and it is offered rather than greyed (${JSON.stringify(avail)})`);

// ── A7.3e-iii — it is its own part, by name ────────────────────────────────
const closed = await askOne('44:', "part '");
check(closed.includes(NEW), `the close names the part that is open (${closed})`);

// ── A7.3e-ii — and by CONTENT, placed in the same session ──────────────────
//
// ⚠ THE ANCESTOR GOES DOWN FIRST, AT THE SAME CELL. A stamp is last-writer-wins,
// so placing `house/cottage` and reading `16:0,0` says what that cell holds
// WITHOUT the authored edge; placing the new part over it and reading again says
// the edge arrived through the part. One cell, two placements, one instrument —
// and the first is the control that keeps the second from passing on a server that
// placed the ancestor either time.
g.ws.send('7:0,0,0.5236');
await until(() => g.says.some((s2) => s2.startsWith('placed ')),
                'the walker was never placed');
const placedFrom = await askOne(`14:12,${FROM}`, 'stencil ');
check(placedFrom.includes('placed'), `the part it came from places (${placedFrom})`);
check(placedFrom.includes(`'${FROM.split('/').pop()}'`),
      `and names ITSELF, not the new part (${placedFrom})`);
const wallsFrom = await askOne('16:0,0', 'walls ');
check(wallsFrom === authoredBefore,
      `the ancestor does not carry the edit (${wallsFrom} vs ${authoredBefore})`);

const placedNew = await askOne(`14:12,${NEW}`, 'stencil ');
check(placedNew.includes('placed'), `the new part places in the same session (${placedNew})`);
// ⚠ A7.3e-iii's real check: the acknowledgement is the author's only confirmation
// of WHICH part landed, and it used to say 'cottage' for both.
// ⚠ DERIVED FROM `NEW`, NOT SPELLED OUT. This read `'annexe'` and broke the day
// the constant above changed — a second spelling of one fact, in a gate whose own
// subject is a part carrying its own name.
check(placedNew.includes(`'${NEW.split('/').pop()}'`),
      `and it announces its own name, not its ancestor's (${placedNew})`);
const wallsNew = await askOne('16:0,0', 'walls ');
check(wallsNew === authored,
      `what was authored is in the cells it stamped (${wallsNew} vs ${authored})`);

// ── A7.3e-iv — a family that does not exist yet ────────────────────────────
lines = await stepFor(`44:${FROM}`, `part '${FROM}'`);
check(said(lines, `part '${FROM}'`).includes('opened'), 'the part opens again');
const famSaved = await askOne(`8:${FAM}`, 'part ');
check(famSaved.includes('saved'),
      `a save into a family that does not exist goes through: ${JSON.stringify(famSaved)}`);
// ⚠ THE HALF THAT WAS SILENT. The acknowledgement said this before the fix too,
// over a file that was never created — so *it said yes* and *the bytes are there*
// are separate claims and only the second is the property.
check(existsSync(`${ROOT}/${FAM}.hxw`),
      `and the bytes are actually there (${FAM}.hxw)`);
check(await libraryFollows(), 'the new family reaches the catalogue too');
const withFam = partsOf(g.cats[g.cats.length - 1]).map((f) => f[1]);
check(withFam.includes(FAM), `and is listed (${withFam.join(',')})`);
check(onDisk().includes(FAM), 'the gate can see it on disk itself');

// ── A7.3e-v — a name the catalogue could never show ────────────────────────
//
// ⚠ REFUSED BEFORE THE WRITE, not cleaned up after. `part_list` walks ONE level,
// so `a/b/c` would be a file in the library that no catalogue can offer and no
// `14:` can place: the author's work, gone, with the save reporting success.
const deep = await askOne('8:a/b/c', 'part save refused');
check(deep !== '', `a two-level name is refused: ${JSON.stringify(deep)}`);
check(deep.includes('one level'), `and says what to type instead (${deep})`);
check(!existsSync(`${ROOT}/a/b/c.hxw`) && !existsSync(`${ROOT}/a`),
      'and nothing was written, not even the directory');
const empty = await askOne('8:house/', 'part save refused');
check(empty !== '', `an empty part name is refused (${JSON.stringify(empty)})`);
check(!existsSync(`${ROOT}/house/.hxw`), 'and no `.hxw` was left in the family');

// ⚠ THE CONTROL FOR THE WHOLE FENCE, and without it every check above passes on a
// server that refuses every save-as. A bare name with no family at all is legal —
// `part_list` lists the top level too.
const bare = await askOne('8:leanto_probe', 'part ');
check(bare.includes('saved'), `a part with no family still saves (${bare})`);
check(existsSync(`${ROOT}/leanto_probe.hxw`), 'and lands at the library root');
await stepFor('44:', "part '");

verdict(g, 'part_new', check);
